apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-writer-binding
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: role-bindings
subjects:
  - kind: User
    name: system:serviceaccount:grafana:update-token
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: configmap-writer
  apiGroup: rbac.authorization.k8s.io
