apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: grafana
  name: configmap-writer
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: role
rules:
  - apiGroups: [""]
    verbs: ["get", "update"]
    resources: ["configmaps"]
    resourceNames: ["gnocchi-datasource"]
