apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: grafana
  name: secrets-reader
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: ["secrets"]
    resourceNames: ["openstack-auth", "kops-auth"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: grafana
  name: configmap-writer
rules:
  - apiGroups: [""]
    verbs: ["get", "list", "write"]
    resources: ["configmaps"]
    resourceNames: ["gnocchi-datasource"]
