apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-token
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: service-account
secrets:
  - name: update-token-token-g52g4
