apiVersion: v1
kind: ConfigMap
metadata:
  name: gnocchi-datasource
  namespace: grafana
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Gnocchi
        type: gnocchixyz-gnocchi-datasource
        typeName": "Gnocchi"
        typeLogoUrl: "public/plugins/gnocchixyz-gnocchi-datasource/docs/gnocchi-logo.png"
        access: proxy
        url: "https://gnocchi.it-mil1.entercloudsuite.com"
        user: ""
        database: ""
        basicAuth: false
        isDefault: true
        jsonData:
          auth-mode: token
          mode: token
          token: "gAAAAABjBJbRwoZvlG4dug5hyg7Nqzv-Xunka3d1NDOFdgU-TGFgr1Zao2npZm-xZxOkaw6vwgpUn88wnPLif11PYTvzeLWncmSBwMUV4z85Qa-1MG8khadEenchZb1Hmg-_81pDdCNIewPeSF9lhIDM2JLfldFNSN-GEbJM1TVMy9SMOpQCUrI"
        readOnly: true
