apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-token
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: cronjob
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: docker-hub
          nodeName: test-cluster-2-node-ukp8dm
          serviceAccountName: update-token
          containers:
            - name: update-token
              image: intothevoid/gnocchi-token-renewal
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: openstack-auth
                    optional: false
          restartPolicy: Never
