apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-token
  namespace: grafana
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-token
              image: openstacktools/openstack-client
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: openstack-auth
                    optional: false
              args: ["/bin/bash", "-c", "/usr/bin/openstack", "token", "issue"]
              # args: ["/bin/bash", "-c", "printenv | grep OS_"]
          restartPolicy: Never
